# Left side / central side

CONFIG_ZMK_USB=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_GPIO=y

# Disable OLED/display/I2C for testing on the clone board.
# CONFIG_ZMK_DISPLAY is not set
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN is not set
# CONFIG_SSD1306 is not set
# CONFIG_I2C is not set
# CONFIG_ZMK_WIDGET_LAYER_STATUS is not set
# CONFIG_ZMK_WIDGET_BATTERY_STATUS is not set
