CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

CONFIG_ZMK_BLE=y
CONFIG_GPIO=y

# CONFIG_ZMK_USB is not set
# CONFIG_ZMK_STUDIO is not set
# CONFIG_ZMK_DISPLAY is not set
# CONFIG_SSD1306 is not set
# CONFIG_I2C is not set
